spring.application.name=urlcondenser

# =========================
# Banco de Dados
# =========================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:urlcondenser}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

# =========================
# JPA / Hibernate
# =========================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.bytecode.provider=bytebuddy

# =========================
# Flyway Migration
# =========================
spring.flyway.baseline-on-migrate=true

# =========================
# Swagger / OpenAPI
# =========================
springdoc.swagger-ui.path=/swagger
springdoc.api-docs.enabled=${SPRINGDOC_ENABLED:true}
springdoc.swagger-ui.enabled=${SPRINGDOC_ENABLED:true}

# =========================
# Servidor
# =========================
server.port=${PORT:8080}
app.base-url=${APP_BASE_URL:http://localhost:8080}

# =========================
# Frontend (CORS)
# =========================
frontend.url=${FRONTEND_URL:http://localhost:5501}

# =========================
# Error Handling
# =========================
server.error.include-stacktrace=never

# =========================
# JWT Secret Key
# =========================
api.security.token.secret=${API_SECURITY_TOKEN_SECRET}