CREATE TABLE tb_urls (
    id BIGSERIAL PRIMARY KEY,
    original_url VARCHAR(2000) NOT NULL,
    short_code VARCHAR(10) NOT NULL UNIQUE,
    clicks BIGINT DEFAULT 0,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
